SELECT B.YEAR, B.M - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM ECOLI_DATA A JOIN
(
SELECT CAST(SUBSTR(DIFFERENTIATION_DATE, 1,4) AS YEAR) AS "YEAR", MAX(SIZE_OF_COLONY) AS M
FROM ECOLI_DATA
GROUP BY CAST(SUBSTR(DIFFERENTIATION_DATE, 1,4) AS YEAR)
) B
ON SUBSTR(A.DIFFERENTIATION_DATE, 1, 4) = B.YEAR
ORDER BY B.YEAR, YEAR_DEV